-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 20:50:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `domdb` DEFAULT CHARACTER SET utf8 ;
USE `domdb` ;

-- -----------------------------------------------------
-- Table `domdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(100) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `dt_created` DATE NOT NULL,
  `dt_updated` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_UNIQUE` ON `domdb`.`users` (`user` ASC);


-- -----------------------------------------------------
-- Table `domdb`.`sheets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domdb`.`sheets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_user` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `hi_protection` INT(10) NOT NULL,
  `hi_protection_max` INT(10) NOT NULL,
  `deleted_at` DATE NOT NULL,
  `copper_coins` INT NOT NULL DEFAULT 0,
  `silver_coins` INT NOT NULL DEFAULT 0,
  `golden_coins` INT NOT NULL DEFAULT 0,
  `notes` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `pk_user`
    FOREIGN KEY (`fk_user`)
    REFERENCES `domdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `user_idx` ON `domdb`.`sheets` (`fk_user` ASC);


-- -----------------------------------------------------
-- Table `domdb`.`inventory_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domdb`.`inventory_itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_sheet` INT NOT NULL,
  `name_item` VARCHAR(255) NOT NULL,
  `desc_item` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_inventory`
    FOREIGN KEY (`fk_sheet`)
    REFERENCES `domdb`.`sheets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inventory_idx` ON `domdb`.`inventory_itens` (`fk_sheet` ASC);


-- -----------------------------------------------------
-- Table `domdb`.`attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domdb`.`attributes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_sheet` INT NOT NULL,
  `attributes_name` VARCHAR(100) NOT NULL,
  `points` INT(10) NOT NULL,
  `points_max` INT(10) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_attributes`
    FOREIGN KEY (`fk_sheet`)
    REFERENCES `domdb`.`sheets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_attributes_idx` ON `domdb`.`attributes` (`fk_sheet` ASC);


-- -----------------------------------------------------
-- Table `domdb`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domdb`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_skill` VARCHAR(100) NOT NULL,
  `desc_skill` VARCHAR(255) NOT NULL,
  `fk_sheet` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `skills`
    FOREIGN KEY (`fk_sheet`)
    REFERENCES `domdb`.`sheets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `skills_idx` ON `domdb`.`skills` (`fk_sheet` ASC);

USE `domdb` ;

-- -----------------------------------------------------
-- Placeholder table for view `domdb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domdb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `domdb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domdb`.`view1`;
USE `domdb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
